name: Green-Next
on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  next:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { token: ${{ secrets.GH_TOKEN }} }
      - id: todo
        run: |
          if grep -q '\[ \]' TEST_LIST.md; then
            echo "left=true" >> $GITHUB_OUTPUT
          else
            echo "left=false" >> $GITHUB_OUTPUT
          fi
      - name: Call Claude Code (red for next task)
        if: steps.todo.outputs.left == 'true'
        env: { ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }} }
        run: |
          npm i -g @anthropic-ai/claude-code
          pip install claude-code-sdk
          python cc_auto.py red
