name: Plan-on-Issue

on:
  issues:
    types: [opened]

jobs:
  plan:
    if: contains(github.event.issue.labels.*.name, 'ai_request')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { token: ${{ secrets.GH_TOKEN }} }

      # ★ Node 20 を用意
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # ★ Convex CLI と Claude Code をグローバルインストール
      - run: |
          npm i -g convex @anthropic-ai/claude-code
          pip install --upgrade pip claude-code-sdk

      - name: Call Claude Code (plan)
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: python cc_auto.py plan --msg "${{ github.event.issue.body }}"